[package]
name = "scrs"
version = "0.1.0"
authors = ["Ethan Smith <ethan@ethanhs.me>"]
edition = "2018"

[dependencies]
num-complex = "0.2"
ndarray = { version = "0.12.1", features = ["blas"] }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }
better-panic = "*"
cmaes = { git = "https://github.com/ethanhs/cmaes", branch = "testsingle" }

[lib]
name = "search_compiler"
path = "src/lib.rs"

[[bin]]
name = "test_srcrs"
path = "src/main.rs"
