[package]
name = "scrs"
version = "0.1.0"
authors = ["Ethan Smith <ethan@ethanhs.me>"]
edition = "2018"

[dependencies]
num-complex = "0.2"
ndarray = { version = "0.12.1", features = ["blas"], path="/home/ethanhs/ndarray" }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }
better-panic = "*"
enum_dispatch = { path = "/home/ethanhs/enum_dispatch" }
cmaes = { git = "https://github.com/ethanhs/cmaes", branch = "testsingle" }
rayon = "1.1"
num_cpus = "*"
numpy = "0.6.0"

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]


[lib]
name = "search_compiler"
path = "src/lib.rs"
crate-type = ["dylib"]

[[bin]]
name = "test_srcrs"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true