[package]
name = "scrs"
version = "0.1.0"
authors = ["Ethan Smith <ethan@ethanhs.me>"]
edition = "2018"

[dependencies]
num-complex = { version = "0.2", features = ["serde"] }
ndarray = "0.13"
enum_dispatch = { git = "https://github.com/ethanhs/enum_dispatch.git" }
numpy = "0.7"
rblas = { version = "*", git = "https://github.com/ethanhs/rust-blas" }
libc = "0.2"
num-traits = "0.2"
reduce = "0.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2"
better-panic = "0.2"
complexmat = { path = "./complexmat" }
md5 = "0.7"

[dependencies.pyo3]
version = "0.8.3"
features = ["extension-module"]


[lib]
name = "search_compiler_rs"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
