[package]
name = "scrs"
version = "0.1.0"
authors = ["Ethan Smith <ethan@ethanhs.me>"]
edition = "2018"

[dependencies]
num-complex = {version = "0.2", features = ["serde"] }
ndarray = "0.12.1"
enum_dispatch = { git = "https://github.com/ethanhs/enum_dispatch.git" }
numpy = "0.6.0"
rblas = { version = "*", git = "https://github.com/ethanhs/rust-blas" }
libc = "*"
num-traits = "0.2"
reduce = "0.1"
serde = {version = "1.0", features = ["derive"] }
bincode = "1.1.4"
better-panic = "*"

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]


[lib]
name = "search_compiler_rs"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "test_srcrs"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true
